version: '3.8'
services:
  flutter_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_dev_build
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8085:8085" # Web development
    command: sleep infinity
    network_mode: host